### PR TITLE
Test Issue2

### LINKED ISSUE #5: Test Issue
This is an issue to illustrate GitHub Project Board Automation

### PR DESCRIPTION
**Pull request by gsorensen**
Fixes #5

### CODE REVIEW

**Review by Havard-SL — COMMENTED** [review]
Unclear description.

**Comment by gsorensen** [comment]
tEST

**Review by Havard-SL — CHANGES_REQUESTED** [review]
test

**Review by Havard-SL — APPROVED** [review]
Seems good!

**Review by Havard-SL — CHANGES_REQUESTED** [review]
bad

**Comment by gsorensen** [comment]
no good

**Review by Havard-SL — APPROVED** [review]
good

**Pull request merged**
